micronaut:
    application:
        name: micronaut-demo
    server:
      cors:
        enabled: true

---
datasources:
  default:
    url: jdbc:h2:mem:micronaut-demo;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

---
datasources.default: {}